### ISSUE TITLE
OS versions counter looks wrong

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#117]
We have only 2 OS versions and the counter shows 4.

![image](https://github.com/rancher/elemental-ui/assets/6025636/491f8878-e5ed-423b-8863-3389e3ef449e)

## Env
```
rancher 2.7.2
elemental-ui extension: 1.2.0
elemental-operator: latest dev - 5.3:1.2.3
```

Finally, not sure if the issue comes from UI because the counter looks right if I use this channel `registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal-dev-channel/5.3:latest`

![image](https://github.com/rancher/elemental-ui/assets/6025636/84314ba7-f51e-4eff-87ed-07c22875515b)

**Comment by aalves08** [comment]
This is known side effect of the new logic, since the OS versions can now contain elements of type `container` and of type `iso`. The `iso` is not to be shown here, but the count still refers to the overall count of the resource type. Nothing to be done about it since the logic of the sidebar is directly tied to whatever information Rancher Dashboard get from a `/counts` endpoint.
The `provisioning.cattle.io.cluster` is another example on the UI where the count is wrong if you have imported Harvester clusters, since those are filtered out from that resource list.

My vote is to close this issue as the time and effort to fix such a thing clearly out-weights the benefits here.

FYI @kwwii

**Comment by kwwii** [comment]
If the count will never be correct, we should rethink the design. Allowing for obvious errors is only going to cause confusion and should be avoided.
