### ISSUE TITLE
`Mach. Inv. Selectors` and `Mach. Inv. Selec. Templates` should not be abbreviated in OS Management > Advanced

### ISSUE THREAD

**Issue by markusewalker** [rancher/elemental-ui#20]
**Setup**
- Rancher version: `v2.7.0-rc1`
- Browser type & version: Chrome

**Describe the bug**

Within OS Management, when looking under the Advanced dropdown, you see the following:

![image](https://user-images.githubusercontent.com/52591819/192337919-c8e9d95f-a54e-45b3-bdcf-421f1caab26a.png)

The `Mach. Inv. Selectors` and `Mach. Inv. Selec. Templates` are abbreviated when they should not be; the full names should be shown. When I view this, I should see `Machine Inventory Selectors` and `Machine Inventory Selector Templates`, respectfully.

**To Reproduce**

1. Setup Rancher with the elemental operator applied and login to the UI.
2. Navigate to OS Management > Admin; view the abbreviated text.

**Result**
There is abbreviated text in the OS Management > Advanced dropdown.

**Expected Result**

There should be no abbreviated text in the OS Management > Advanced dropdown.

**Comment by kwwii** [comment]
If we stick to naming things according to the resource names there is no way around shortening this text. If a normal ellipsis were used it would read "Machine Inventory Selectors" and "Machine Inventory Selector...". As there is no rule against abbreviation from a UX standpoint this issue is not valid.
