### ISSUE TITLE
Download ISO from SeedImage menu

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#99]
I wonder if it would make sense to be able to download ISO directly from the SeedImage menu:
![image](https://user-images.githubusercontent.com/6025636/233287815-3b76e91d-c941-4810-bd2e-788e8cc9b2d2.png)
Something like adding a `Download` button.

I'm asking because if you trigger a build in machine registration endpoint and then you navigate to another menu, you lose the ability to download and you have to build again.

@aalves08 @fgiudici WDYT?

**Comment by fgiudici** [comment]
Yep, looks a great idea to me! If *it is not that hard to implement* (only @aalves08 could tell!), that could be a smart way to allow to re-download built ISO.

**Comment by aalves08** [comment]
It's not hard to implement, since the url is there (if the iso build succeeds).

One comment is that the `Seed Image` resource wasn't even supposed to appear "as a page" under Elemental and now we are putting "more" effort into it.

We should have a discussion with @kwwii during an Elemental sync just to make sure the user experience for the next version (not the one about to release) is going to leverage the usage of this resource as a "usable interface" because I was under the impression that we were supposed to "kill" this once we have a way to clean up the seed images automatically.

**Comment by juadk** [comment]
> It's not hard to implement, since the url is there (if the iso build succeeds).
> 
> One comment is that the `Seed Image` resource wasn't even supposed to appear "as a page" under Elemental and now we are putting "more" effort into it.
> 
> We should have a discussion with @kwwii during an Elemental sync just to make sure the user experience for the next version (not the one about to release) is going to leverage the usage of this resource as a "usable interface" because I was under the impression that we were supposed to "kill" this once we have a way to clean up the seed images automatically.

Ah, so maybe I can postpone this https://github.com/rancher/elemental/issues/788

**Comment by juadk** [comment]
Could be also valuable to keep `SeedImage` menu and leverage it to configure cloud-init (I know we said to keep advanced usage like that one to cmdline but...), I'm thinking about a form like we have to create a registration endpoint. Let's add @kkaempf and @agracey  to the discussion.

**Comment by agracey** [comment]
> Re-building a SeedImage is cheap and will happen as you iterate to create the perfect ISO image for your hardware/usecase.

This is going to be especially true once the base isos are coming from an OCI artifact that can be better cached

**Comment by juadk** [comment]
Ok let's close it then and as we discussed during the sync meeting, SeedImage menu will be removed in favor of adding a list in Registration Endpoint, I can also close the automation task around the SeedImage menu.
